export interface Branch {
  id: string
  name: string
  city: "jakarta" | "bali" | "lombok"
  address: string
  phone: string
  whatsapp: string
  email: string
  hours: {
    weekday: string
    weekend: string
  }
  services: string[]
  bookingservices?: string[]
  image: string
  coordinates: {
    lat?: number
    lng?: number
  }
  featured?: boolean
}

export const BRANCHES: Branch[] = [
  {
    "id": "jj-pet-house-jakarta",
    "name": "JJ PET HOUSE JAKARTA",
    "city": "jakarta",
    "address": "Jl. Radio Dalam Raya Gandaria Utara, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12140",
    "phone": "0819-1298-2996",
    "whatsapp": "0819-1298-2996",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 48.jpeg",
    "coordinates": {},
    "featured": false
  },
  
  {
    "id": "jj-pet-house-denpasar",
    "name": "JJ PET HOUSE",
    "city": "bali",
    "address": "Jl. Tukad Batanghari No.77, Dauh Puri Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80225",
    "phone": "0811-3999-893",
    "whatsapp": "0811-3999-893",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 48.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-dalung",
    "name": "JJ PET DALUNG",
    "city": "bali",
    "address": "Jl. Perum Dalung Permai Blok oo No.23, Dalung, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    "phone": "0813-3990-7700",
    "whatsapp": "0813-3990-7700",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-kesambi",
    "name": "JJ PET KESAMBI",
    "city": "bali",
    "address": "Jl. Raya Kesambi No.80x, Kerobokan, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    "phone": "0813-5353-9669",
    "whatsapp": "0813-5353-9669",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-house-mataram",
    "name": "JJ PET HOUSE MATARAM",
    "city": "lombok",
    "address": "Jl. Abdul Kadir Munsyi No.18, Punia, Kec. Mataram, Kota Mataram, Nusa Tenggara Barat 83125",
    "phone": "0811-346-755",
    "whatsapp": "0811-346-755",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-house-udayana",
    "name": "JJ PET HOUSE UDAYANA",
    "city": "bali",
    "address": "Jl. Raya Uluwatu No.130, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80362",
    "phone": "0857-3962-9606",
    "whatsapp": "0857-3962-9606",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-house-balian",
    "name": "JJ PET HOUSE BALIAN",
    "city": "bali",
    "address": "Jl. Tukad Balian No.133A, Renon, Denpasar Selatan, Kota Denpasar, Bali 80221",
    "phone": "0811-3810-3349",
    "whatsapp": "0811-3810-3349",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-uluwatu",
    "name": "JJ PET ULUWATU",
    "city": "bali",
    "address": "Jl. Raya Uluwatu, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    "phone": "081353782922",
    "whatsapp": "081353782922",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Hotel", "Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "josh-pet-shop",
    "name": "JOSH PET SHOP",
    "city": "bali",
    "address": "Jl. Raya Uluwatu, Ungasan, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    "phone": "082146491803",
    "whatsapp": "082146491803",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Pet Shop"],
    "bookingservices": [],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-tuban",
    "name": "JJ PET TUBAN",
    "city": "bali",
    "address": "Jl. Raya Tuban No.5, Tuban, Kec. Kuta, Kabupaten Badung, Bali 80361",
    "phone": "082146491803",
    "whatsapp": "082146491803",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-nusa-dua",
    "name": "JJ PET NUSA DUA",
    "city": "bali",
    "address": "Jl. Siligita No.50, Benoa, Kec. Kuta Sel., Kabupaten Badung, Bali 80363",
    "phone": "082146491803",
    "whatsapp": "082146491803",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-pecatu",
    "name": "JJ PET PECATU",
    "city": "bali",
    "address": "Jl. Raya Uluwatu Pecatu, Pecatu, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    "phone": "081353782922",
    "whatsapp": "081353782922",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-batubulan",
    "name": "JJ PET BATUBULAN",
    "city": "bali",
    "address": "Jln Raya Sukawati No.7, Kec. Sukawati, Gianyar, Bali (sebelah Kimora)",
    "phone": "082146491803",
    "whatsapp": "082146491803",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-peliatan",
    "name": "JJ PET PELIATAN",
    "city": "bali",
    "address": "Br. Teruna, Jl. Cok Gede Rai, Peliatan, Kecamatan Ubud, Kabupaten Gianyar, Bali 80471",
    "phone": "081236197288",
    "whatsapp": "081236197288",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-kedewatan",
    "name": "JJ PET KEDEWATAN",
    "city": "bali",
    "address": "Jl. Raya Lungsiakan No.99, Kedewatan, Kecamatan Ubud, Kabupaten Gianyar, Bali 80561",
    "phone": "081236197288",
    "whatsapp": "081236197288",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-sidakarya",
    "name": "JJ PET SIDAKARYA",
    "city": "bali",
    "address": "Jl. Sidakarya No.38C, Sesetan, Denpasar Selatan, Kota Denpasar, Bali 80224",
    "phone": "08174792021",
    "whatsapp": "08174792021",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-pemogan",
    "name": "JJ PET PEMOGAN",
    "city": "bali",
    "address": "Jl. Raya Pemogan No.240, Pemogan, Denpasar Selatan, Kota Denpasar, Bali 80221",
    "phone": "08174792021",
    "whatsapp": "08174792021",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-tabanan-1",
    "name": "JJ PET TABANAN 1",
    "city": "bali",
    "address": "Jl. Gatot Subroto, Banjar Anyar, Kec. Kediri, Kabupaten Tabanan, Bali 82121",
    "phone": "081805334959",
    "whatsapp": "081805334959",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-tabanan-2",
    "name": "JJ PET TABANAN 2",
    "city": "bali",
    "address": "Budi Utomo Jl. Dr. Ir. Soekarno No.Dekat, Dauh Peken, Kec. Kediri, Kabupaten Tabanan, Bali 82113",
    "phone": "0822-1116-1644",
    "whatsapp": "0822-1116-1644",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-kerobokan",
    "name": "JJ PET KEROBOKAN",
    "city": "bali",
    "address": "Shop 1, Jl. Raya Anyar No.30, Kerobokan, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    "phone": "087861796249",
    "whatsapp": "087861796249",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "moon-pet-shop",
    "name": "MOON PET SHOP",
    "city": "bali",
    "address": "Shop 1, Jl. Raya Anyar No.30, Kerobokan, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    "phone": "087860357785",
    "whatsapp": "087860357785",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-canggu",
    "name": "JJ PET CANGGU",
    "city": "bali",
    "address": "Jl. Raya Canggu, Tibubeneng, Kec. Kuta Utara, Kabupaten Badung, Bali 80361",
    "phone": "087861796249",
    "whatsapp": "087861796249",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-munggu",
    "name": "JJ PET MUNGGU",
    "city": "bali",
    "address": "Jl. By Pass Tanah Lot No.8, Munggu, Kec. Mengwi, Kabupaten Badung, Bali 80351",
    "phone": "087861796249",
    "whatsapp": "087861796249",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jovy-pet-shop",
    "name": "JOVY PET SHOP",
    "city": "bali",
    "address": "Jl. By Pass Tanah Lot No.8, Munggu, Kec. Mengwi, Kabupaten Badung, Bali 80351",
    "phone": "087861796249",
    "whatsapp": "087861796249",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Pet Shop"],
    "bookingservices": ["grooming", "boarding", "clinic"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-kunti",
    "name": "JJ PET KUNTI",
    "city": "bali",
    "address": "Jl. Kunti II, Jl. Raya Basangkasa No.09, Seminyak, Kec. Kuta, Kabupaten Badung, Bali 80361",
    "phone": "087762922170",
    "whatsapp": "087762922170",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-jimbaran",
    "name": "JJ PET JIMBARAN",
    "city": "bali",
    "address": "654Q+93W, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361",
    "phone": "0887433029739",
    "whatsapp": "0887433029739",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-ubud",
    "name": "JJ PET UBUD",
    "city": "bali",
    "address": "Jl. Raya Pengosekan No.2013, MAS, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",
    "phone": "085172044580",
    "whatsapp": "085172044580",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-bilok",
    "name": "JJ PET BILOK",
    "city": "bali",
    "address": "Jl. Tukad Bilok No.90D, Sanur Kauh, Denpasar Selatan, Kota Denpasar, Bali 80227",
    "phone": "0895413365511",
    "whatsapp": "0895413365511",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-nangka",
    "name": "JJ PET NANGKA",
    "city": "bali",
    "address": "Jl. Nangka Utara No.265, Tonja, Kec. Denpasar Utara, Kota Denpasar, Bali 80239",
    "phone": "0895413365511",
    "whatsapp": "0895413365511",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  },
  {
    "id": "jj-pet-imbo",
    "name": "JJ PET IMBO",
    "city": "bali",
    "address": "Jl. Imam Bonjol No.495B, Pemecutan Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80119",
    "phone": "081918300888",
    "whatsapp": "081918300888",
    "email": "",
    "hours": { "weekday": "08:00 - 21:00", "weekend": "08:00 - 22:00" },
    "services": ["Grooming", "Pet Shop"],
    "bookingservices": ["grooming"],
    "image": "/image/Pict 32.jpeg",
    "coordinates": {},
    "featured": false
  }
 
]

export const CITIES = [
  { id: "jakarta", name: "Jakarta", icon: "🌆", count: 4 },
  { id: "bali", name: "Bali", icon: "🏝️", count: 4 },
  { id: "lombok", name: "Lombok", icon: "🏖️", count: 3 },
]
